### ISSUE TITLE
Add support for Pre/Post migrate hooks

### ISSUE THREAD

**Issue by marcosnils** [marcosnils/cmt#2]
The migration flow would be as follows:
- Validations (CPU / Memory / CRIU/RUNC versions, etc, IP, file transfer)
- Checkpoint
- Copy files
  
  (restore-before) >> Cambiar la ruta de AWS                             
- Restore  
  (restore-fail) >> if restore fails  
  (restore-success) >> cleanup

**Comment by marcosnils** [comment]
Add support for rollback hook in case restore fails.

**Comment by xetorthio** [comment]
Done
